name: CI

on:
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'docs/**'
      
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.julia-threads }} thread(s) - ${{ github.event_name }}
    runs-on: ubuntu-latest
    env:
      JULIA_NUM_THREADS: ${{ matrix.julia-threads }}
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
    strategy:
      matrix:
        group:
          - Core
        version:
          - '1' #this will use latest stable v1.x.y version; if break, can go to CI to look at previous successful builds
        julia-threads:
          - '1'
          - '2'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1